/** Static assets exported from the Figma "KBC mobile home" frame (node 10:3133). */
const BASE = "/figma/kbc-home";

export const FIGMA_ASSETS = {
  bellOff: `${BASE}/bell-off.svg`,
  iosSignal: `${BASE}/ios-signal.svg`,
  iosWifi: `${BASE}/ios-wifi.svg`,
  iosBatteryFull: `${BASE}/ios-battery-full.svg`,
  settings: `${BASE}/settings.svg`,
  search: `${BASE}/search.svg`,
  kateMark: `${BASE}/kate-mark.svg`,
  notifications: `${BASE}/notifications.svg`,
  shortcutWalletCards: `${BASE}/shortcut-wallet-cards.svg`,
  newspaper: `${BASE}/newspaper.svg`,
  shortcutHouse: `${BASE}/shortcut-house.svg`,
  signpost: `${BASE}/signpost.svg`,
  accountPiggyBank: `${BASE}/account-piggy-bank.svg`,
  accountWalletCards: `${BASE}/account-wallet-cards.svg`,
  facetLightA: `${BASE}/facet-light-a.svg`,
  facetLightB: `${BASE}/facet-light-b.svg`,
  facetLightC: `${BASE}/facet-light-c.svg`,
  facetNavyA: `${BASE}/facet-navy-a.svg`,
  facetNavyB: `${BASE}/facet-navy-b.svg`,
  facetNavyC: `${BASE}/facet-navy-c.svg`,
  pencil: `${BASE}/pencil.svg`,
  bankMark: `${BASE}/bank-mark.svg`,
  chevronUp: `${BASE}/chevron-up.svg`,
  tipHouse: `${BASE}/tip-house.svg`,
  tipCoins: `${BASE}/tip-coins.svg`,
  slidersHorizontal: `${BASE}/sliders-horizontal.svg`,
  arrowLeftRight: `${BASE}/arrow-left-right.svg`,
  handHelping: `${BASE}/hand-helping.svg`,
  moreOptionsLight: `${BASE}/more-options-light.svg`,
  moreOptions: `${BASE}/more-options.svg`,
  brandMark: `${BASE}/brand-mark.svg`,
  addBadge: `${BASE}/add-badge.svg`,
  circleX: `${BASE}/circle-x.svg`,
  gift: `${BASE}/gift.svg`,
  cashCoins: `${BASE}/cash-coins.svg`,
  navWalletCards: `${BASE}/nav-wallet-cards.svg`,
  navList: `${BASE}/nav-list.svg`,
  navPiggyBank: `${BASE}/nav-piggy-bank.svg`,
  navBriefcaseBusiness: `${BASE}/nav-briefcase-business.svg`,
  navLayers: `${BASE}/nav-layers.svg`,
} as const;
